### ISSUE TITLE
[BUG]Viewport scrolls down

### ISSUE THREAD

**Issue by AmjadHD** [randy3k/Terminus#130]
![terminus](https://user-images.githubusercontent.com/33235928/59132916-b2c65780-8976-11e9-8a1d-95492930d86c.gif)

when first opening the terminal panel (here cmd) the viewport is scrolled down, and doesn't show the first text.
when you place the cursor in it's normal position, it is scrolled down again.

OS: Windows 10
Terminus: v0.2.31
Note that this issue is older, but I fail to remember when it was first introduced.

**Comment by randy3k** [comment]
I could reproduce a related bug in a different project on a windows server 2019. It was a project which uses the same python dependency pywinpty. It seems that when the process starts, pywinpty sends more than enough line feeds. The same bug was not seen on windows server 2016.

**Comment by randy3k** [comment]
added a note:
https://github.com/randy3k/Terminus#cmdexe-rendering-issue-in-panel

I don't think there is fix for this issue. It seems that it only affects cmd.exe and powershell is not affected.

**Comment by AmjadHD** [comment]
It looks like this issue was fixed
![image](https://user-images.githubusercontent.com/33235928/68528760-4d94da80-02f7-11ea-97d6-bd9578a81bf2.png)
I checked that this has nothing to do with terminus (I checked out v0.2.34), but I recently updated windows to v1903 maybe they fixed it ?

**Comment by randy3k** [comment]
Some improvements have been applied, but I still see some random insertion of new lines when passing enters in cmd prompt.
